# Obsidian Notes

name: obsidian-notes
parent: default

matches:
  - trigger: ":done"
    replace: "✅"

  - trigger: ":prog"
    replace: "🚧"

  - trigger: ":change"
    replace: "🚨"

  - trigger: ":budding"
    replace: "[[🌿 Budding]]"

  - trigger: ":evergreen"
    replace: "[[🌳 Evergreen]]"

  - trigger: "ever-exp"
    replace: |
             State: [[🌱 Seedling]]

             Associations:

             ### Notes
             
             -

  - trigger: ":ready"
    replace: "Ready to be Recorded"

  - trigger: ":goal"
    replace: "⛳️ - ☐ $|$"

  - trigger: "goal-exp"
    replace: |
             Associations: [[Goal]]

             ### Notes
             
             - $|$

             ### Milestones
             
             -

  - trigger: "header-exp"
    replace: "#### $|$"

  - trigger: ":base"
    replace: "♦︎"

  - trigger: ":mile"
    replace: "Ⓜ - ☐ $|$"

  - trigger: "mile-exp"
    replace: |
             Associations: [[Milestones]]

             ### Notes
             
             - $|$

             ### Intentions
             
             - 

  - trigger: "int-exp"
    replace: |
             ### Clocks

             - Estimate:

             - Start Time:

             - End Time:

             ### Result (total time and explain if I go over my estimate)

             ### Notes

             - $|$

  - trigger: "misc-exp"
    replace: |
             Associations:

             ### Notes

             - $|$

  - trigger: ":morning"
    replace: "Morning Pages ({{mydate}})"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m-%d-%Y"

  - trigger: "morn-exp"
    replace: |
             Associations: [[Morning Pages]]

             Thoughts:
             
             $|$

             Associated Comments/Pages
             -

  - trigger: ":re-int"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y - ☐"

  - trigger: ":re-task"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y Misc - ☐"

  - trigger: "rsc-exp"
    replace: |
             ### Metadata

             - Associations: $|$

             - Author:

             - Link:

             ### Notes

             -
  - trigger: "rsc-article"
    replace: |
             ### Metadata

             - Associations: [[Resource]] [[Article]]

             - Author: $|$

             - Link:

             ### Notes

             -

  - trigger: "rsc-book"
    replace: |
             ### Metadata

             - Associations: [[Resource]] [[Book]]

             - Author: $|$

             - Link:

             ### Notes

             -

  - trigger: "rsc-course"
    replace: |
             ### Metadata

             - Associations: [[Resource]] [[Course]]

             - Author: $|$

             - Link:

             ### Notes

             -

  - trigger: "rsc-pres"
    replace: |
             ### Metadata

             - Associations: [[Resource]] [[Presentation]]

             - Author: $|$

             - Link:

             ### Notes

             -

  - trigger: "rsc-video"
    replace: |
             ### Metadata

             - Associations: [[Resource]] [[video]]

             - Author: $|$

             - Link:

             ### Notes

             -

  - trigger: ":todo"
    replace: "☐"
  
  - trigger: ":inter"
    replace: "Interruptions ({{mydate}})"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m-%d-%Y"
  
  - trigger: "inter-exp"
    replace: |
             Associations: [[Interruptions]]

             ### Notes

             - $|$